Dockerfile

FROM ubuntu
RUN echo "hello world" >/tmp/sravan1
:wq!    ###build##
1. go to in side container to check /tmp file show you "hello world"
######################

FROM ubuntu
WORKDIR /tmp
RUN echo "this is sravan file" >/tmp/sravan1
ENV name anu
COPY file1 /tmp
ADD test.tar.gz /tmp

:wq!    ###run###  
1 ,this will faile becouse local not there file1 so
vi file1 
this si my file
2. above naot there    tar   file   so vecan create locally
touch test
tar -cvf test.tar test        ####this is command for create tar filr    RED   #####
ll
3. so now unzip that   tar   RED file
gzip test.tar
ll         ## show you test.tar.gz##

docker start cont2
docker attach cont2
#/tmp container entry 
ll      it show u all file
cat sravan1       
echo $name
o/p anu 
###########################################


######################
